# Generated by Django 6.0.1 on 2026-01-19 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('students_count', models.IntegerField(default=0)),
                ('school_type', models.CharField(choices=[('davlat', 'davlat maktabi'), ('xususiy', 'Xususiy maktab')], default='davlat', max_length=50)),
                ('director_name', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
