# Generated by Django 6.0.1 on 2026-01-23 11:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dars1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('grade', models.CharField(choices=[('grade1', '1-sinf'), ('grade2', '2-sinf'), ('grade3', '3-sinf'), ('grade4', '4-sinf'), ('grade5', '5-sinf'), ('grade6', '6-sinf'), ('grade7', '7-sinf'), ('grade8', '8-sinf'), ('grade9', '9-sinf'), ('grade10', '10-sinf'), ('grade11', '11-sinf'), ('grade12', '12-sinf')], default='grade1', max_length=40)),
                ('joined_at', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('school', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dars1.school')),
            ],
        ),
    ]
